# Generated by Django 3.1.4 on 2021-01-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='post_pics/'),
        ),
    ]
