# Generated by Django 3.1.4 on 2021-01-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210110_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_pics/default.png', upload_to='post_pics/'),
        ),
    ]
